### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by danshev** [Pr0Ger/PyAPNs2#1]
Thank you for your work on this, I'm getting the following error:

```
File "/usr/local/lib/python2.7/dist-packages/apns2-0.1.0-py2.7.egg/apns2/payload.py", line 48, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by danshev** [comment]
I guess this is a Python 2.7 vs 3.0 issue.

**Comment by skrew** [comment]
I got the same problem with python 2.7. I had patched with:

`super(Payload, self).__init__()`

**Comment by danshev** [comment]
Thank you -- that's exactly what I ended up doing ... unfortunately, I then found out that Hyper doesn't support Python 2.7.6.

**Comment by Pr0Ger** [comment]
Yes, it's definitely 2.* vs 3.* issue. I limit support for > 3.3 for two reasons: 2.* branch is legacy and I don't use it in new projects. Also, I want to add `asyncio` support in future (that's why library version is 0.1 now), which is also limited to the version higher than 3.3.
