### ISSUE TITLE
BadDeviceToken after upgrading to 0.7.1 and Python 3.5

### ISSUE THREAD

**Issue by knawwxbackme** [Pr0Ger/PyAPNs2#102]
Hi there! I just updated to python 3.5 and needed to update to 0.7.1 and after I've done that it seems as though it keeps giving me back a BadDeviceToken response. I haven't changed any of the code or the device tokens. I could really use some help with this. Thanks!

**Comment by Ozdat** [comment]
Same issue here

**Comment by russellhoff** [comment]
Same exception here, using Python 3.9 and Django 3.2. Thinking on switching to another library...
