### ISSUE TITLE
How send notification with image?

### ISSUE THREAD

**Issue by MBakhtiyor** [Pr0Ger/PyAPNs2#105]
I used PayloadAlert with parameters but image didn;t show. 
`alert = PayloadAlert(body="Hello World!", title="Hello", launch_image="my_image.jpg"`

Please help me how to send push notification with custom iange?

**Comment by jasques** [comment]
This is the code I am using to send a notification that is then showing the image in a notification.
FYI you will need to interpret it in your iOS project - it will not show by itself.

```python
custom_payload = {"data": {"attachment-url": public_url_to_the_image}}
alert = PayloadAlert(title=title, body=body)
p = Payload(
                    alert=alert,
                    mutable_content=True,
                    custom=custom_payload,
                    sound="default",
                    badge=0,
)
```
