### ISSUE TITLE
Unable to send notifications using proxy host and port

### ISSUE THREAD

**Issue by bharat-gera** [Pr0Ger/PyAPNs2#120]
We are using proxy server to send the notification. While sending the notifications using proxy_host and proxy_port following error is coming:

```
Traceback (most recent call last):
  File "apns_2_test.py", line 8, in <module>
    client.send_notification(token_hex, payload)
  File "/tmp/temp_env/lib/python3.6/site-packages/apns2/client.py", line 93, in send_notification
    stream_id = self.send_notification_async(token_hex, notification, topic, priority, expiration, collapse_id)
  File "/tmp/temp_env/lib/python3.6/site-packages/apns2/client.py", line 145, in send_notification_async
    stream_id = self._connection.request('POST', url, json_payload, headers)  # type: int
  File "/tmp/temp_env/lib/python3.6/site-packages/hyper/http20/connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/tmp/temp_env/lib/python3.6/site-packages/hyper/http20/connection.py", line 544, in endheaders
    self.connect()
  File "/tmp/temp_env/lib/python3.6/site-packages/hyper/http20/connection.py", line 366, in connect
    assert not self.proxy_host, "Proxy with HTTPS not supported."
```
**My code**:
```
from apns2.client import APNsClient
from apns2.payload import Payload

token_hex = '<token>'
payload = Payload(alert="Hello World!", sound="default", badge=1)
client = APNsClient("<apns-cert>",use_alternative_port=True, use_sandbox=True, proxy_host="xx.xxx.xx.x",proxy_port=8080)
client.send_notification(token_hex, payload)
```
Any help would be really appreciated.

**Comment by najtek** [comment]
As you can see in your traceback, proxy is not supported by hyper in version that PyAPNs2 depends on.
Proxy support was added to hyper later, check this https://github.com/python-hyper/hyper/commit/185254bd22ace87f4e650f1bfe645c8a3f002c9f
You can either fork PyAPNs2 and change dependencies, or upgrade hyper package after installing apns2 (`pip install --upgrade git+https://github.com/python-hyper/hyper.git@<commit_id>`)

**Comment by bharat-gera** [comment]
Thank you for your replies!

We are using latest version of hyper==0.7.0 which have proxy support. I have tested the same with proxy but no luck. Same same issue is occurring on the server.
Please check once.

**Comment by bharat-gera** [comment]
@najtek Thanks for the support and reply! It's working now, My bad that I wasn't identified the `hyper` version issue.
