### ISSUE TITLE
Where's extra flag?

### ISSUE THREAD

**Issue by dzpt** [Pr0Ger/PyAPNs2#127]
Ver 1 has extra flag which i can pass dict to it.
like `extra={"url":"deeplink"}`
Now on the payload, i can't pass it anymore

**Comment by blakegong** [comment]
Are you looking for `custom`? https://github.com/Pr0Ger/PyAPNs2/blob/5e4a938cd2e24249f6345aac27ba783defa5a63f/apns2/payload.py#L117-L118
