### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by ipranjal** [Pr0Ger/PyAPNs2#136]
Getting the following SSL error when I am trying to use my voip service pem file 
Getting same kind of error in both python 3.6 and 3.9

```
  File "/home/ubuntu/nvenv/lib/python3.9/site-packages/apns2/client.py", line 56, in __init__
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]:     self.__credentials = CertificateCredentials(credentials, password)  # type: Credentials
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]:   File "/home/ubuntu/nvenv/lib/python3.9/site-packages/apns2/credentials.py", line 37, in __init__
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]:     ssl_context = init_context(cert=cert_file, cert_password=password)
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]:   File "/home/ubuntu/nvenv/lib/python3.9/site-packages/hyper/tls.py", line 131, in init_context
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]:     context.load_cert_chain(cert, password=cert_password)
Sep 22 13:08:32 ip-10-0-0-117 gunicorn[2333]: ssl.SSLError: [SSL] PEM lib (_ssl.c:4065)
```

**Comment by ssakone** [comment]
@ipranjal  how you done it, this issue?
i have the same issue.

**Comment by rvanassche** [comment]
same error 
    client = APNsClient('certificat.pem', use_sandbox=False, use_alternative_port=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/.local/lib/python3.11/site-packages/apns2/client.py", line 56, in __init__
    self.__credentials = CertificateCredentials(credentials, password)  # type: Credentials
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/.local/lib/python3.11/site-packages/apns2/credentials.py", line 37, in __init__
    ssl_context = init_context(cert=cert_file, cert_password=password)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/.local/lib/python3.11/site-packages/hyper/tls.py", line 131, in init_context
    context.load_cert_chain(cert, password=cert_password)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3938)
