### ISSUE TITLE
ssl.SSLZeroReturnError

### ISSUE THREAD

**Issue by SearchDream** [Pr0Ger/PyAPNs2#142]
The APNs service keep getting this error since yesterday, anyone knows what's the reason? Thanks

**Comment by ajans** [comment]
It is common behavior for the APNs service to close connections on their end at will.

Over the last 6 months, 2/3 of our push-attempts failed on first try.
That is why you should check for common SSL-errors like that and retry in such cases with a fresh connection.
After the retries, all the 2nd push-attempts went through for us.

**Comment by SearchDream** [comment]
> It is common behavior for the APNs service to close connections on their end at will.
> 
> 
> 
> Over the last 6 months, 2/3 of our push-attempts failed on first try.
> 
> That is why you should check for common SSL-errors like that and retry in such cases with a fresh connection.
> 
> After the retries, all the 2nd push-attempts went through for us.

Thanks for your sharing. I only get this error from yesterday.

**Comment by SearchDream** [comment]
> ssl.SSLZeroReturnError

ssl.SSLZeroReturnError is a subclass of ssl.SSLError, maybe that's the reason you haven't get this error yet.

**Comment by SearchDream** [comment]
I have add code to capture ssl.SSLError and retry, but still got ssl.SSLError from one of the service. I can confirm the error report from the second try for push notification.

**Comment by SearchDream** [comment]
Close the underlaying HTTP2 connection before the second try seems fixed the issue, no ssl.SSLError anymore.
