### ISSUE TITLE
Compatibility with Mac M1 (Python 3.10)

### ISSUE THREAD

**Issue by Paulo-Jorge-PM** [Pr0Ger/PyAPNs2#143]
Hi,
Any plans or tips on supporting the most recent version of Python (3.10)? 

Mac M1 only supports natively Python 3.10, so using this library on it doesn't work.

Any tips or plans on that?

Thanks

**Comment by jonesnc** [comment]
@Paulo-Jorge-PM I've had some luck with the[ `apns2-up`](https://pypi.org/project/apns2-up/) fork, which installs the versions of the dependencies that are Python 3.10 compatible.

**Comment by Paulo-Jorge-PM** [comment]
@jonesnc mega thanks for the feedback, we'll try it fingers crossed. Best regards
