### ISSUE TITLE
Can't get voip notifications to work 

### ISSUE THREAD

**Issue by ennisthemenace** [Pr0Ger/PyAPNs2#17]
I am trying to send voip notifications so I need to change the server and port to use gateway.sandbox.push.apple.com  but when I do so I just get loads of errors I can't figure out if http2 is problem.

**Comment by leovp** [comment]
Post your stack trace & errors you encounter.

**Comment by javierquevedo** [comment]
What type of certificate are you using?
The Apple Push Notification service SSL (Sandbox & Production) certificate, which is supposed to work for Voip notifications, did not work for us.

We had no issues using the VoIP Services Certificate.
