### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xfox** [Pr0Ger/PyAPNs2#20]
Hello! Thanks for your library.

I've found memory leak in client.py: APNsClient. send_notification. 
After getting HTTP20Response you should call HTTP20Response.close() or wraps it with context. If you don't close response Stream objects will leak. It leaks slowly but my service sends millions of pushes daily and it takes 8GB ram for 2 days.
Please, fix it.

Thanks!

**Comment by masakichi** [comment]
@xfox Did do find that if not close the steam, may raise `TooManyStreamsError: Max outbound streams is 500, 500 open`  error?

**Comment by xfox** [comment]
I didn't get this exception until I've ran this patch on production. With unclosed streams memory are leaked, but there weren't any exceptions like TooManyStreamsError.

The patch fixed memory leak, but after few hours I've got exception you mentioned. I am investigating it now.

**Comment by masakichi** [comment]
@xfox FYI
https://github.com/Lukasa/hyper/issues/264
https://github.com/Lukasa/hyper/issues/289

**Comment by xfox** [comment]
Thank you. I haven't find the reason of TooManyStreamsError yet and just added reconnect if it's happened.

**Comment by Pr0Ger** [comment]
Since PR is merged, I'm closing this for now
