### ISSUE TITLE
SSLError(1, u'[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:590)')}

### ISSUE THREAD

**Issue by shashfrankenstien** [Pr0Ger/PyAPNs2#24]
I'm running a server on Ubuntu. It was working fine until recently. I suspect that it happened when I ran an apt upgrade. I'd appreciate any information about this error.

**Comment by Pr0Ger** [comment]
Looks like it's an error when handshake. Possible reasons:
1) Push certificate is expired
2) Old Python version which doesn't support TLS1.2
3) Something in the middle intercepting with connection to APNs, so secure connection can't be made

**Comment by alexislg2** [comment]
I have same issue. Points 1. and 2. ar ok. How to check point 3?

**Comment by riccardoSocialcities** [comment]
Hey there @Pr0Ger 
I am having the same issue of @shashfrankenstien.
The cert is not expired, I am testing with an iOS app called Easy APNs Provider and it works :(
Python 2.7.12

Any idea?

**Comment by armaanahluwalia** [comment]
@riccardoSocialcities Did you ever get to the bottom of that issue? Facing the same thing here.

**Comment by Vadim-Karpenko** [comment]
Same here, got this error - `ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1056)`

**Comment by vimiPonyai** [comment]
i think this library have too many issue not handle.
