### ISSUE TITLE
[Feature request] Connection pool

### ISSUE THREAD

**Issue by tamakisquare** [Pr0Ger/PyAPNs2#44]
Excerpt from the [official docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) on _Best Practices for Managing Connections_,

> **Keep your connections with APNs open across multiple notifications; do not repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack**. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day, it is acceptable practice to use a new connection each day.

I think it's the best for _apns2-client_ library to conform to this best practice, in order to avoid the possibility of having the services built with the library being seeing as a denial-of-service attack and thus interruption to those services. Therefore, I think we should add a connection pool for managing the reuse of open connections to this library.

Thanks for developing this library. It has been working great for me and its code is easy to read and follow.

**Comment by vinnyspb** [comment]
But does the library actually open-close connections constantly? My understanding was that connection is left opened after the first push, and then you can reuse it as many times as you want from as many threads as you want.

Thread-safety assumption comes from hyper package [changelog](https://pypi.python.org/pypi/hyper/0.6.0) (used for HTTP20Connection class):

> The HTTP20Connection object is now thread-safe, so long as stream IDs are used on all method calls.

And as it is a HTTP/2 connection, library heavily reuses streams inside a single connection, which per my understanding is not the same as a connection pool of course, but gives you similar benefits.

Maybe the author could comment more on that.

**Comment by tamakisquare** [comment]
@vinnyspb, good point! I missed out the fact that *PyAPNs2* relies on *http20*, so I was expecting to see code managing connection at the *PyAPNs2* library level and I didn't see any. As it turns out, I checked out the source code of the *http20* package after seeing your comment, the connection management has already been well taken care of by *http20*. Thanks for your insight.

**Comment by avium** [comment]
> My understanding was that connection is left opened after the first push, and then you can reuse it as many times as you want from as many threads as you want.

I'm concerned there may be thread-safety issues. For example, `send_notification_batch()` doesn't seem to take into account that there may be open streams pending from other calls to that method on other threads. If I'm not mistaken, this could result in too many (or more than `__max_concurrent_streams`) simultaneous requests.
