### ISSUE TITLE
custom key

### ISSUE THREAD

**Issue by LarkinBTCC** [Pr0Ger/PyAPNs2#45]
how can i add custom keys to payload?

**Comment by Pr0Ger** [comment]
You can pass dict with your custom keys as a `custom` parameter for `Payload` class
https://github.com/Pr0Ger/PyAPNs2/blob/master/apns2/payload.py#L48-L50

**Comment by Dubrzr** [comment]
What if we want to put custom keys in result['aps'] sub-dictionary?

**Comment by Pr0Ger** [comment]
You shouldn't add custom keys to `aps` sub-dictionary since it's reserved for Apple usage.
About replacing parameters with `**kwargs` I dislike this approach because autocompletion doesn't play well with it, also explicit args can replace documentation in some way

**Comment by Dubrzr** [comment]
So in the case I'm forced to add custom keys to aps sub-dictionary (let's say I work at Apple), I cannot with your library unless I create my own CustomPayload class... smart...
