### ISSUE TITLE
check for credential string with is instance does not work correct in python 2

### ISSUE THREAD

**Issue by pfennema** [Pr0Ger/PyAPNs2#48]
In python 2, the check whether the credential passed is a string or not is not correct as the string passed is a unicode string and hence the check will not pass. The end result leads to an attribute error in __init_connection. Offending code:

    def __init__(self, credentials, use_sandbox=False, use_alternative_port=False, proto=None, json_encoder=None, password=None):
        if credentials is None or isinstance(credentials, str):  # Should be either unicode or basestring for python 2
            self.__credentials = CertificateCredentials(credentials, password)
        else:
            self.__credentials = credentials
 

I changed it for now to test for unicode instance, however I get an IOError exception further down the road. Will investigate further.

**Comment by royge** [comment]
We also experience this issue. We need to explicitly cast unicode to str.
