### ISSUE TITLE
StreamResetError while running on VM

### ISSUE THREAD

**Issue by miteshnath** [Pr0Ger/PyAPNs2#49]
Hey, 
So, we have a Django app which uses this library for push notifications. We have succesfully tested this on our local machine and its running fine. But on our production server after deployment, we  are getting StreamResetError .
![error_apns](https://user-images.githubusercontent.com/10214827/28476832-1a2e9150-6e6f-11e7-977a-0323be950293.png) 
What's wrong?

**Comment by navyad** [comment]
after long debug something wrong is happening in here

https://github.com/Lukasa/hyper/blob/development/hyper/http20/connection.py#L728
