### ISSUE TITLE
'apns-expiration' header is not honoured

### ISSUE THREAD

**Issue by subhadipghoshal** [Pr0Ger/PyAPNs2#50]
We have been using this client to send notifications through APNS to iPhones. 

Here is the client and the send_notification function

`apns_client = APNsClient(settings.APNS_CERT_PATH, use_sandbox=True, use_alternative_port=False)`
`results = apns_client.send_notification_batch(notifications, APPID_IOS, expiration=ttl, collapse_id=apns_collapse_id)`

We have a specific requirement where we require the notification to be expired 45 seconds post sending. However, the expiration time as such is not honoured. We ran a test scenario where we sent a notification to a device while it was offline, and we brought it up online after 55 seconds. The notification still reached, even though the expiration time was set at 45 seconds. 

Along with that, we have also been experimenting with notifications with apns-expiration = 0. According to Apple's documentation

> If the value is 0, APNs treats the notification as if it expires immediately and does not store the notification or attempt to redeliver it.

However, when we sent out a notification to a device which we brought online 10 seconds after sending it out, the notification still reached, even though expiration was set to zero. 

Is there something we are missing? Or is it something on the side of APNS? Any help would be greatly appreciated.

Thanks in advance.

Python Version - 3.5.1

**Comment by Pr0Ger** [comment]
I'm not sure, but maybe this header is used only if first delivery is failed (e.g. device suddenly became unavailable). But for the first delivery, there is a different rule: 

> If APNs attempts to deliver a notification and the destination device is offline, APNs stores the notification for a limited period of time and delivers it when the device becomes available again. This component stores only the most recent notification per device and per app.

Also, expiration header requires timestamp after which notification is no longer relevant instead of ttl
