### ISSUE TITLE
Connection with alternative port fails

### ISSUE THREAD

**Issue by PaulosV** [Pr0Ger/PyAPNs2#59]
When trying to connect to both development and production APNS HTTP/2 servers on the alternative port (2197), the connection is reset upon creation. When using the regular 443 port, the connection is established.

**Expected behavior:** The connection should be successfully established using both ports, 443 and 2197.

**Cause:** If a port different than 443 is used, then the `hyper` library does not create secure connection by default. Apple servers expect TLS connection. This behavior of `hyper` can be overriden by `secure=True` in the `HTTP20Connection` constructor.

**Proposed solution:** I propose #58 which adds a `secure=True` to the `HTTP20Connection` initialization.

**Comment by Pr0Ger** [comment]
#58 is now merged, so this can be closed
