### ISSUE TITLE
Request for new Release on pypi.org

### ISSUE THREAD

**Issue by ajans** [Pr0Ger/PyAPNs2#62]
Could you please publish a new release to pypi.org?
There were some major improvements since last release 0.3.0 in May 2017.
Especially proxy-support and improvements to connection-handling are very needed.

**Comment by Paulo-Branco** [comment]
+1

**Comment by chrisnovak** [comment]
+1

**Comment by Pr0Ger** [comment]
Yeah, it's time to release an update. 0.4.0 is live on PyPi.

**Comment by ajans** [comment]
Thank you! :-)
