### ISSUE TITLE
Provide instructions for generating key.pem certificate file

### ISSUE THREAD

**Issue by greencoder** [Pr0Ger/PyAPNs2#7]
I've been trying to generate the `key.pem` certificate needed to create the connection to Apple's servers, but I haven't been able to get it working. Could you please provide the steps you used to generate a working file?

Using these instructions:
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW11

I've been able to export either a `.p12` file or a `.cer` file when selecting both the `Apple Push Services` certificate and the private key under Keychain Assistant > My Certificates.

Thanks!

**Comment by greencoder** [comment]
I might have figured this out thorough trial-and-error. After generating the `.p12` file, I ran this command to convert it into a `.pem` file:

```
$ openssl pkcs12 -in certificate.p12 -out key.pem -nodes
```

Once I did that, PyAPNs2 was able to use it. Hope this helps someone else.

**Comment by Pr0Ger** [comment]
Most likely anyone who needs such an instruction will try to search in StackOverflow, not here.

Anyway, there is one more way to do it (and it's my favorite): just use [`pem`](https://github.com/fastlane/fastlane/tree/master/pem) tool for generating push certificates from console in `pem`/`p12` format
