### ISSUE TITLE
TopicDisallowed when using VoIP or Watch "Complications"

### ISSUE THREAD

**Issue by spditner** [Pr0Ger/PyAPNs2#70]
Took a bit of time to figure out what this was supposed to be set to. I originally thought it was just the app id, i.e com.example.yourApp as noted in the README -- however for VoIP pushes, you have to add a .voip suffix (see "APNs Provider Certificates" in the [Apple Docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html)), same goes for Watch where you have to add a .complication suffix.

**Comment by ninwjf** [comment]
topic = 'com.example.yourApp.voip'

**Comment by Pr0Ger** [comment]
I'm not sure how to clarify it in README, maybe add mention that topic is not always equal to bundle id or even add some examples
