### ISSUE TITLE
Recommended heartbeat_period value

### ISSUE THREAD

**Issue by srcreigh** [Pr0Ger/PyAPNs2#72]
Hi, regarding the `heartbeat_period` method of keeping a connection from breaking during periods of inactivity, is there a recommended default value?

@arthur-a in your PR you mentioned that "when connection is not used for several minutes" the connection may break. In your example you use 10 seconds. I imagine it may be safe to use 60s or 120s. What do you recommend?

Also, @Pr0Ger, would you accept a PR to enable the heartbeat_period by default, or a PR to update the README about its usage?

**Comment by srcreigh** [comment]
Link to PR in question: https://github.com/Pr0Ger/PyAPNs2/pull/63

**Comment by arthur-a** [comment]
It depends of settings of some proxies between your application and APNs. I think it better when heartbeat period is not greater than 30 seconds.
