### ISSUE TITLE
PyPi version including the heartbeat_period commit

### ISSUE THREAD

**Issue by srcreigh** [Pr0Ger/PyAPNs2#73]
Hi, the last version 0.4.1 was released in May, however I would like to use changes merged in July. Could you make a new release on PyPi (0.4.2)?

**Comment by srcreigh** [comment]
For now we have added this to requirements.txt.

```
# apns2==0.4.1
git+git://github.com/Pr0Ger/PyAPNs2@ad899c22ab6c7d8066166a75f22cd1da006fe90f#egg=apns2
```

**Comment by Pr0Ger** [comment]
Hi, it's been a long time, but a new release is available now https://pypi.org/project/apns2/0.5.0/
