### ISSUE TITLE
apns-push-type cannot be present with voip push

### ISSUE THREAD

**Issue by matthewh** [Pr0Ger/PyAPNs2#87]
I'm getting **InvalidPushType** when attempting to send a VOIP push with apns-push-type specified.

**Comment by eliburke** [comment]
This started failing on Sept 19th for us, the day iOS 13 was released (literally, working in the afternoon on the 18th, failing in the morning on the 19th). _apns-push-type_ cannot be set to _alert_ or to _background_ or it reports an error and is not delivered to clients. 

We did not test it with other values, but with a forked copy of PyAPNs2 that does not set _apns-push-type_ our VOIP push notifications started working again.

**Comment by Pr0Ger** [comment]
Looks like Apple recently added few new types of notifications (voip, complication, fileprovider, mdm) and also lifted requirement that this field is required (now it is only required for notifications for watchOS 6). I'll release an update to reflect this changes tonight

**Comment by 72squared** [comment]
Seems like you should also handle the `InvalidPushType` response here?

https://github.com/Pr0Ger/PyAPNs2/blob/master/apns2/errors.py#L170-L200
