### ISSUE TITLE
can not choice push host at develpoment or production 

### ISSUE THREAD

**Issue by liansheng** [Pr0Ger/PyAPNs2#98]
server only  
```python
SANDBOX_SERVER = 'api.sandbox.push.apple.com'
LIVE_SERVER = 'api.push.apple.com'
```
can push to develpoment host

**Comment by Pr0Ger** [comment]
what is "development host"?

**Comment by liansheng** [comment]
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

**Comment by liansheng** [comment]
> what is "development host"?

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

**Comment by Pr0Ger** [comment]
You can pass `use_sandbox=True` to `APNsClient` constructor for sending pushes to sandbox environment

**Comment by liansheng** [comment]
thk  that's work for me .  i can't find sendbox host in apple docment, only `Development server: api.development.push.apple.com:443`
